"""
Quiz Router for SkillTwin Roadmap
Handles AI-powered quiz generation, validation, and node unlocking for roadmap progression.
"""

import uuid
import json
import re
from datetime import datetime
from typing import List, Optional, Dict, Any, Tuple
from fastapi import APIRouter, Depends, Query, HTTPException, status, Header
from sqlalchemy import func
from sqlalchemy.orm import Session
from pydantic import BaseModel

from backend.database import get_db
from backend.shared.models import (
    QuizQuestionModel,
    QuizAttemptModel,
    TaskProgressModel,
    TASK_SKILL_MAP,
    TASK_SEQUENCE
)
from backend.routers.auth import get_user_id_from_token
from backend.shared.llm_client import llm_client

router = APIRouter(
    prefix="/api/quiz",
    tags=["AI Quiz System for Roadmap Progression"]
)


# =========================================================
# Pydantic Schemas
# =========================================================

class QuizOptionSchema(BaseModel):
    id: int
    text: str


class QuizQuestionSchema(BaseModel):
    id: str
    question_text: str
    options: List[QuizOptionSchema]
    difficulty: str
    skill_name: str


class QuizSubmissionSchema(BaseModel):
    question_id: str
    selected_answer_index: int


class QuizResultSchema(BaseModel):
    question_id: str
    is_correct: bool
    correct_answer_index: int
    explanation: Optional[str]


class QuizResponseSchema(BaseModel):
    questions: List[QuizQuestionSchema]
    total_questions: int
    passing_score: int  # Percentage required to pass
    generated_by: str = "ai"  # Indicates if generated by AI


class QuizValidationRequest(BaseModel):
    user_id: str
    task_id: str  # The roadmap task this quiz is for
    submissions: List[QuizSubmissionSchema]
    time_taken_seconds: Optional[int] = None


class QuizValidationResponse(BaseModel):
    passed: bool
    score_percentage: int
    correct_answers: int
    total_questions: int
    results: List[QuizResultSchema]
    task_unlocked: bool
    next_task_id: Optional[str] = None
    message: str


class SkillQuizStatusResponse(BaseModel):
    task_id: str
    skill_name: str
    is_unlocked: bool
    is_completed: bool
    best_score: Optional[int] = None
    total_quizzes_taken: int


# =========================================================
# AI Quiz Generation System
# =========================================================

# Skill descriptions for context-aware question generation
SKILL_CONTEXTS = {
    "HTML/CSS": "Fundamentals of web development including semantic HTML5, CSS3, Flexbox, Grid, responsive design, and modern CSS features like custom properties.",
    "JavaScript": "Core JavaScript including ES6+ features, async/await, promises, DOM manipulation, closures, prototypes, and modern browser APIs.",
    "React": "React library including functional components, hooks (useState, useEffect, useContext), JSX, state management, component patterns, and React 18 features.",
    "TypeScript": "TypeScript type system including interfaces, generics, utility types, type guards, and best practices for type-safe React applications.",
    "Redux": "Redux state management including Redux Toolkit, slices, createAsyncThunk, and modern state management patterns.",
    "Node.js": "Server-side JavaScript with Node.js including Express.js, REST API design, middleware patterns, and server architecture.",
    "Python/FastAPI": "Python web frameworks with FastAPI including path operations, Pydantic models, dependency injection, and async programming.",
    "Authentication": "Web authentication including JWT tokens, OAuth, password hashing with bcrypt, session management, and security best practices.",
    "PostgreSQL": "Relational database with PostgreSQL including SQL queries, joins, aggregations, indexing, transactions, and database design patterns.",
    "ORM": "Object-Relational Mapping with SQLAlchemy including models, relationships, migrations, queries, and efficient database access patterns.",
    "Docker": "Containerization with Docker including Dockerfiles, images, containers, docker-compose, multi-stage builds, and deployment.",
    "CI/CD": "Continuous Integration/Deployment with GitHub Actions including workflows, testing automation, and deployment pipelines.",
    "Testing": "Software testing including unit tests, integration tests, Jest, React Testing Library, and test-driven development.",
    "Security": "Web application security including OWASP Top 10, XSS, CSRF, SQL injection prevention, and secure coding practices.",
    "Portfolio": "Personal portfolio website development with responsive design, deployment, and showcasing projects.",
    "E-commerce": "Building e-commerce applications with shopping carts, product filtering, state management, and payment integration basics.",
    "Backend": "Backend development concepts including REST APIs, server architecture, database integration, and API security.",
    "Database": "Database design and management including relational modeling, SQL, indexing strategies, and data integrity.",
    "DevOps": "DevOps practices including containerization, CI/CD pipelines, cloud deployment, and infrastructure management.",
    "Capstone": "Full-stack application development combining all learned skills into a production-ready capstone project."
}


async def generate_ai_questions(
    skill_name: str,
    question_count: int = 5,
    user_level: str = "intermediate"
) -> List[Dict[str, Any]]:
    """
    Generate quiz questions using AI (OpenRouter/LLM).
    Creates contextual, relevant questions based on the skill and user's level.
    """
    skill_context = SKILL_CONTEXTS.get(skill_name, f"General {skill_name} concepts")

    system_prompt = """You are an expert technical educator creating quiz questions for a skill development platform.
Generate multiple-choice quiz questions that test practical knowledge, not just theoretical facts.
Each question should have exactly 4 options with one clearly correct answer.
Include a brief explanation for why the correct answer is right.

IMPORTANT: Return your response as valid JSON in this exact format:
{
    "questions": [
        {
            "question_text": "The question here?",
            "options": ["Option A", "Option B", "Option C", "Option D"],
            "correct_answer_index": 0,
            "explanation": "The correct answer is A because...",
            "difficulty": "Easy/Medium/Hard"
        }
    ]
}

Make questions practical and relevant to real-world coding scenarios."""

    user_prompt = f"""Generate {question_count} multiple-choice quiz questions about {skill_name}.
Skill context: {skill_context}
User level: {user_level}

Create questions that:
1. Test practical understanding, not just memorization
2. Include realistic scenarios a developer might encounter
3. Have one clearly correct answer
4. Have plausible but incorrect distractors

Return only the JSON format specified."""

    try:
        result = await llm_client.extract_structured_json(
            messages=[{"role": "user", "content": user_prompt}],
            system_prompt=system_prompt
        )

        if result.get("error"):
            print(f"[Quiz AI] Error generating questions: {result['error']}")
            return []

        data = result.get("data", {})
        questions = data.get("questions", [])

        print(f"[Quiz AI] Generated {len(questions)} questions for {skill_name}")
        return questions

    except Exception as e:
        print(f"[Quiz AI] Exception generating questions: {e}")
        return []


# =========================================================
# Fallback Questions (when AI fails or for demo)
# =========================================================

# Minimum number of questions a quiz must contain to be worth grading. Below
# this a single lucky guess swings the score past the 70% pass mark.
MIN_QUIZ_QUESTIONS = 3

# When a skill has no question bank of its own, fall back to the closest skill
# that does. Only genuinely adjacent topics are listed: an off-topic quiz that
# still unlocks the next node is worse than no quiz at all, so a skill with no
# sensible neighbour is deliberately absent and yields a 503 instead.
FALLBACK_SKILL_ALIASES: Dict[str, str] = {
    "Frontend": "HTML/CSS",
    "Portfolio": "HTML/CSS",
    "TypeScript": "JavaScript",
    "Redux": "React",
    "E-commerce": "React",
    "Backend": "Node.js",
    "ORM": "PostgreSQL",
    "Database": "PostgreSQL",
    "DevOps": "Docker",
    "CI/CD": "Docker",
}


def get_fallback_questions(skill_name: str) -> Tuple[str, List[Dict[str, Any]]]:
    """
    Hardcoded questions for when AI generation is unavailable.

    Returns (source_skill, questions). The source skill is the skill the
    questions are actually about, which is not always the skill that was asked
    for -- callers must store and display that value rather than the requested
    one, or a Docker quiz ends up full of JavaScript questions labelled Docker.
    Returns ("", []) when nothing on-topic exists.
    """
    fallback_questions = {
        "Python": [
            {
                "question_text": "Which keyword is used to define a function in Python?",
                "options": ["function", "def", "func", "define"],
                "correct_answer_index": 1,
                "explanation": "The `def` keyword is used to define a function in Python.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What data type is the result of: `type([])` in Python?",
                "options": ["<class 'array'>", "<class 'list'>", "<class 'tuple'>", "<class 'dict'>"],
                "correct_answer_index": 1,
                "explanation": "Empty square brackets create a Python list. type() returns the class name.",
                "difficulty": "Easy"
            },
            {
                "question_text": "How do you create a virtual environment in Python?",
                "options": ["python install venv", "python -m venv myenv", "pip install virtualenv", "python create env"],
                "correct_answer_index": 1,
                "explanation": "The standard way to create a virtual environment is `python -m venv <name>`.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the output of `len('hello')` in Python?",
                "options": ["4", "5", "6", "Error"],
                "correct_answer_index": 1,
                "explanation": "len() counts the characters. 'hello' has 5 characters.",
                "difficulty": "Easy"
            },
            {
                "question_text": "Which method adds an element to the end of a Python list?",
                "options": ["push()", "append()", "add()", "insert()"],
                "correct_answer_index": 1,
                "explanation": "Python lists use .append() to add elements. push() is JavaScript, insert() inserts at a position.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is a Python decorator?",
                "options": [
                    "A function that wraps another function to extend its behavior",
                    "A way to declare variables",
                    "A type of class",
                    "A package manager"
                ],
                "correct_answer_index": 0,
                "explanation": "A decorator is a function that takes another function and extends its behavior without modifying it.",
                "difficulty": "Medium"
            }
        ],
        "Excel": [
            {
                "question_text": "Which function in Excel returns the number of cells that contain numbers?",
                "options": ["COUNT", "SUM", "NUMBERS", "TOTAL"],
                "correct_answer_index": 0,
                "explanation": "The COUNT function counts cells containing numeric values. COUNTA counts non-empty cells.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does the VLOOKUP function do?",
                "options": [
                    "Validates vertical data",
                    "Looks up a value in the leftmost column and returns a value from the same row",
                    "Calculates vertical sums",
                    "Creates vertical charts"
                ],
                "correct_answer_index": 1,
                "explanation": "VLOOKUP searches for a value in the first column of a range and returns a value in the same row from another column.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the keyboard shortcut to insert a SUM formula in Excel?",
                "options": ["Ctrl+S", "Alt+= (Alt + equals)", "Ctrl+Shift+S", "F2"],
                "correct_answer_index": 1,
                "explanation": "Alt + = (Alt and the equals sign) automatically inserts SUM formula for the selected range.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the difference between a Workbook and a Worksheet in Excel?",
                "options": [
                    "They are the same thing",
                    "A workbook is a file, a worksheet is a single sheet inside it",
                    "A worksheet is a file, a workbook is a sheet",
                    "A workbook is a chart, a worksheet is a table"
                ],
                "correct_answer_index": 1,
                "explanation": "A workbook is the entire Excel file (.xlsx). A worksheet is one of the tabs/sheets within that workbook.",
                "difficulty": "Easy"
            },
            {
                "question_text": "Which chart type is BEST for showing parts of a whole?",
                "options": ["Line chart", "Pie chart", "Scatter plot", "Histogram"],
                "correct_answer_index": 1,
                "explanation": "Pie charts are ideal for showing proportions of a whole. Line charts are for trends over time.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does the IF function do?",
                "options": [
                    "Imports a file",
                    "Returns one value if a condition is true, another if false",
                    "Filters data",
                    "Creates a chart"
                ],
                "correct_answer_index": 1,
                "explanation": "IF(condition, value_if_true, value_if_false) performs conditional logic in Excel.",
                "difficulty": "Easy"
            }
        ],
        "SQL": [
            {
                "question_text": "Which SQL command is used to retrieve data from a database?",
                "options": ["GET", "SELECT", "FETCH", "READ"],
                "correct_answer_index": 1,
                "explanation": "SELECT is the standard SQL command to retrieve data from tables.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does the WHERE clause do?",
                "options": [
                    "Specifies which table to query",
                    "Filters rows based on a condition",
                    "Groups rows together",
                    "Sorts the results"
                ],
                "correct_answer_index": 1,
                "explanation": "WHERE filters rows by a condition. HAVING filters groups, ORDER BY sorts.",
                "difficulty": "Easy"
            },
            {
                "question_text": "Which SQL JOIN returns only rows that have matches in BOTH tables?",
                "options": ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "OUTER JOIN"],
                "correct_answer_index": 2,
                "explanation": "INNER JOIN returns only rows where the join condition is true in both tables.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the difference between WHERE and HAVING?",
                "options": [
                    "No difference",
                    "WHERE filters rows before grouping, HAVING filters groups after",
                    "HAVING is for SELECT only",
                    "WHERE is faster"
                ],
                "correct_answer_index": 1,
                "explanation": "WHERE filters individual rows before GROUP BY. HAVING filters aggregated groups after GROUP BY.",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which aggregate function returns the average value?",
                "options": ["SUM", "AVG", "COUNT", "MEAN"],
                "correct_answer_index": 1,
                "explanation": "AVG() returns the average. SQL uses AVG, not MEAN. SUM adds, COUNT counts rows.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does the PRIMARY KEY constraint ensure?",
                "options": [
                    "The column is hidden",
                    "Each value is unique and not null",
                    "The column is encrypted",
                    "The column is first"
                ],
                "correct_answer_index": 1,
                "explanation": "PRIMARY KEY ensures each row has a unique, non-null identifier.",
                "difficulty": "Easy"
            }
        ],
        "Statistics": [
            {
                "question_text": "What is the median of the values [2, 4, 6, 8, 10]?",
                "options": ["4", "6", "8", "5"],
                "correct_answer_index": 1,
                "explanation": "The median is the middle value. For 5 numbers, it's the 3rd one, which is 6.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does a p-value of 0.03 typically mean?",
                "options": [
                    "The probability of the null hypothesis being true is 3%",
                    "There is a 3% chance the result is due to random variation",
                    "The effect size is 3%",
                    "The sample size is 3"
                ],
                "correct_answer_index": 1,
                "explanation": "A p-value of 0.03 means if the null hypothesis were true, you'd see this result (or more extreme) only 3% of the time by chance.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is standard deviation a measure of?",
                "options": [
                    "The center of the data",
                    "The spread of the data around the mean",
                    "The most common value",
                    "The total range"
                ],
                "correct_answer_index": 1,
                "explanation": "Standard deviation measures the typical distance of values from the mean - a measure of spread/variability.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the difference between population and sample standard deviation?",
                "options": [
                    "No difference",
                    "Population uses n, sample uses n-1 in the denominator (Bessel's correction)",
                    "Population is always larger",
                    "Sample has no variance"
                ],
                "correct_answer_index": 1,
                "explanation": "Sample standard deviation uses n-1 (Bessel's correction) to give an unbiased estimate of the population std.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is correlation?",
                "options": [
                    "Causation between variables",
                    "A statistical measure of how two variables move together",
                    "The difference between two means",
                    "A type of test"
                ],
                "correct_answer_index": 1,
                "explanation": "Correlation measures the strength of a relationship between two variables. Correlation != causation.",
                "difficulty": "Easy"
            }
        ],
        "Machine Learning": [
            {
                "question_text": "What is supervised learning?",
                "options": [
                    "Learning with labeled training data",
                    "Learning without any data",
                    "Learning with no labels",
                    "Learning from reinforcement"
                ],
                "correct_answer_index": 0,
                "explanation": "Supervised learning uses labeled examples to learn a mapping from inputs to outputs.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is overfitting?",
                "options": [
                    "Model is too simple",
                    "Model memorizes training data but fails on new data",
                    "Model trains too slowly",
                    "Model uses too little data"
                ],
                "correct_answer_index": 1,
                "explanation": "Overfitting is when a model learns the training data too well, including its noise, so it generalizes poorly.",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which metric is used for classification accuracy?",
                "options": ["MSE", "RMSE", "Accuracy", "R-squared"],
                "correct_answer_index": 2,
                "explanation": "Accuracy = (correct predictions) / (total predictions). MSE and RMSE are for regression.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the purpose of a train/test split?",
                "options": [
                    "To make training faster",
                    "To evaluate model performance on unseen data",
                    "To reduce data size",
                    "To increase accuracy"
                ],
                "correct_answer_index": 1,
                "explanation": "Train/test split ensures we evaluate the model on data it has never seen during training.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does cross-validation do?",
                "options": [
                    "Validates cross-platform code",
                    "Tests the model on multiple data splits for robust evaluation",
                    "Combines different models",
                    "Reduces training time"
                ],
                "correct_answer_index": 1,
                "explanation": "Cross-validation splits data into k folds and trains/tests on different combinations for more reliable performance estimates.",
                "difficulty": "Medium"
            }
        ],
        "Docker": [
            {
                "question_text": "What is a Docker container?",
                "options": [
                    "A physical box",
                    "A lightweight, portable executable package of an application and its dependencies",
                    "A type of database",
                    "A cloud service"
                ],
                "correct_answer_index": 1,
                "explanation": "A container packages an app with its dependencies so it runs the same anywhere - your laptop or production.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the difference between a Docker image and a container?",
                "options": [
                    "No difference",
                    "An image is a blueprint; a container is a running instance of that image",
                    "A container is a blueprint; an image is a running instance",
                    "They are different operating systems"
                ],
                "correct_answer_index": 1,
                "explanation": "An image is the template (like a class). A container is a running instance of that image (like an object).",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which command builds a Docker image from a Dockerfile?",
                "options": ["docker run", "docker build", "docker pull", "docker push"],
                "correct_answer_index": 1,
                "explanation": "`docker build -t name .` creates an image from the Dockerfile in the current directory.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the purpose of a Dockerfile?",
                "options": [
                    "To store user files",
                    "To define instructions for building a Docker image",
                    "To run a container",
                    "To document a project"
                ],
                "correct_answer_index": 1,
                "explanation": "A Dockerfile contains step-by-step instructions (FROM, RUN, COPY, etc.) for building a Docker image.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does `docker-compose` do?",
                "options": [
                    "Compresses Docker images",
                    "Defines and runs multi-container Docker applications",
                    "Creates Dockerfiles",
                    "Pushes images to registries"
                ],
                "correct_answer_index": 1,
                "explanation": "docker-compose uses a YAML file to define and start multiple containers together (e.g. web + database).",
                "difficulty": "Medium"
            }
        ],
        "Git": [
            {
                "question_text": "What does `git clone` do?",
                "options": [
                    "Creates a new repository",
                    "Makes a local copy of a remote repository",
                    "Deletes a repository",
                    "Renames a repository"
                ],
                "correct_answer_index": 1,
                "explanation": "git clone copies a remote repository (e.g. from GitHub) to your local machine.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the difference between `git pull` and `git fetch`?",
                "options": [
                    "No difference",
                    "fetch downloads changes; pull downloads AND merges them",
                    "pull only works locally",
                    "fetch is for tags only"
                ],
                "correct_answer_index": 1,
                "explanation": "fetch downloads remote changes but doesn't merge. pull does both - fetch + merge in one step.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is a Git branch?",
                "options": [
                    "A copy of the repo on a different server",
                    "An independent line of development",
                    "A type of commit",
                    "A file backup"
                ],
                "correct_answer_index": 1,
                "explanation": "A branch is a parallel line of development. main/master is the default, feature branches let you work without affecting main.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does `git merge` do?",
                "options": [
                    "Combines changes from one branch into another",
                    "Deletes a branch",
                    "Creates a new repository",
                    "Forces a push"
                ],
                "correct_answer_index": 0,
                "explanation": "git merge combines the history of a source branch into the current branch.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is a merge conflict?",
                "options": [
                    "Two files with the same name",
                    "When Git cannot automatically merge because the same lines changed differently",
                    "A failed push",
                    "A missing file"
                ],
                "correct_answer_index": 1,
                "explanation": "A conflict happens when two branches modify the same lines, requiring manual resolution.",
                "difficulty": "Medium"
            }
        ],
        "Linux": [
            {
                "question_text": "Which command lists files in the current directory in Linux?",
                "options": ["dir", "ls", "list", "show"],
                "correct_answer_index": 1,
                "explanation": "`ls` lists files and directories. Use `ls -l` for detailed list, `ls -a` to show hidden files.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does the `cd` command do?",
                "options": [
                    "Copies a directory",
                    "Changes the current directory",
                    "Creates a directory",
                    "Deletes a directory"
                ],
                "correct_answer_index": 1,
                "explanation": "`cd` (change directory) moves you to a different directory. `cd ..` goes up one level.",
                "difficulty": "Easy"
            },
            {
                "question_text": "Which command shows the current directory path?",
                "options": ["whereami", "path", "pwd", "cwd"],
                "correct_answer_index": 2,
                "explanation": "`pwd` (print working directory) shows your current location in the file system.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does `chmod 755 file.txt` do?",
                "options": [
                    "Deletes the file",
                    "Sets permissions: owner can read/write/execute, others can read/execute",
                    "Changes ownership",
                    "Encrypts the file"
                ],
                "correct_answer_index": 1,
                "explanation": "755 = rwxr-xr-x: owner has full access (7), group and others have read+execute (5).",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which command shows the contents of a text file?",
                "options": ["cat", "open", "view", "show"],
                "correct_answer_index": 0,
                "explanation": "`cat` (concatenate) displays file contents. `less` or `more` for paginated viewing.",
                "difficulty": "Easy"
            }
        ],
        "Pandas": [
            {
                "question_text": "How do you read a CSV file into a Pandas DataFrame?",
                "options": ["pd.load('file.csv')", "pd.read_csv('file.csv')", "pd.import_csv('file.csv')", "pd.open('file.csv')"],
                "correct_answer_index": 1,
                "explanation": "`pd.read_csv('file.csv')` is the standard way to load CSV data into a DataFrame.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does `df.head()` do?",
                "options": [
                    "Returns the first 5 rows by default",
                    "Returns the column names",
                    "Removes the first row",
                    "Counts the rows"
                ],
                "correct_answer_index": 0,
                "explanation": "df.head() shows the first 5 rows. Pass a number like df.head(10) to see 10 rows.",
                "difficulty": "Easy"
            },
            {
                "question_text": "How do you get summary statistics of a DataFrame?",
                "options": ["df.summary()", "df.stats()", "df.describe()", "df.info()"],
                "correct_answer_index": 2,
                "explanation": "df.describe() shows count, mean, std, min, max, and quartiles for numeric columns.",
                "difficulty": "Easy"
            },
            {
                "question_text": "How do you filter rows where column 'age' is greater than 30?",
                "options": ["df[df.age > 30]", "df.filter('age > 30')", "df.where('age > 30')", "df.select(age>30)"],
                "correct_answer_index": 0,
                "explanation": "Boolean indexing df[df.age > 30] is the standard way to filter rows in Pandas.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is a Pandas DataFrame?",
                "options": [
                    "A 1D labeled array",
                    "A 2D labeled data structure (like a spreadsheet)",
                    "A type of database",
                    "A visualization library"
                ],
                "correct_answer_index": 1,
                "explanation": "A DataFrame is a 2D table with labeled rows and columns, similar to a spreadsheet or SQL table.",
                "difficulty": "Easy"
            }
        ],
        "NumPy": [
            {
                "question_text": "How do you create a NumPy array from a Python list?",
                "options": ["np.array([1, 2, 3])", "np.list([1, 2, 3])", "np.create([1, 2, 3])", "np.from([1, 2, 3])"],
                "correct_answer_index": 0,
                "explanation": "`np.array([1, 2, 3])` converts a Python list to a NumPy ndarray.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does `np.zeros((3, 4))` create?",
                "options": [
                    "A 1D array of 12 zeros",
                    "A 3x4 matrix filled with zeros",
                    "An array of 3 zeros, repeated 4 times",
                    "A 4x3 matrix filled with zeros"
                ],
                "correct_answer_index": 1,
                "explanation": "np.zeros((rows, cols)) creates a matrix of that shape filled with zeros. (3, 4) means 3 rows, 4 columns.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the difference between a list and a NumPy array?",
                "options": [
                    "No difference",
                    "NumPy arrays are faster, more memory-efficient, and support vectorized operations",
                    "Lists are faster",
                    "Arrays can only hold numbers"
                ],
                "correct_answer_index": 1,
                "explanation": "NumPy arrays are optimized for numerical computation, support vectorized operations, and are much faster than lists for math.",
                "difficulty": "Medium"
            },
            {
                "question_text": "How do you get the shape of a NumPy array?",
                "options": ["arr.size()", "arr.shape", "arr.dim()", "arr.dimensions"],
                "correct_answer_index": 1,
                "explanation": "arr.shape returns a tuple of dimensions, e.g. (3, 4) for a 3x4 matrix.",
                "difficulty": "Easy"
            }
        ],
        "PostgreSQL": [
            {
                "question_text": "Which command creates a new database in PostgreSQL?",
                "options": ["CREATE DB mydb", "CREATE DATABASE mydb", "NEW DATABASE mydb", "DATABASE CREATE mydb"],
                "correct_answer_index": 1,
                "explanation": "CREATE DATABASE mydb is the standard PostgreSQL command to create a new database.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is a primary key in PostgreSQL?",
                "options": [
                    "The first column in a table",
                    "A column or set of columns that uniquely identifies each row",
                    "A password",
                    "The most important column"
                ],
                "correct_answer_index": 1,
                "explanation": "A primary key uniquely identifies each row in a table. It must be unique and not null.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the difference between CHAR and VARCHAR in PostgreSQL?",
                "options": [
                    "No difference",
                    "CHAR is fixed length, VARCHAR is variable length",
                    "VARCHAR is for numbers only",
                    "CHAR is faster"
                ],
                "correct_answer_index": 1,
                "explanation": "CHAR(n) always uses exactly n characters (padding with spaces). VARCHAR(n) uses up to n characters.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is an index in PostgreSQL?",
                "options": [
                    "A list of table names",
                    "A data structure that speeds up data retrieval at the cost of writes",
                    "A type of constraint",
                    "A table backup"
                ],
                "correct_answer_index": 1,
                "explanation": "An index is a separate data structure that lets PostgreSQL find rows quickly without scanning the whole table.",
                "difficulty": "Medium"
            }
        ],
        "Authentication": [
            {
                "question_text": "What does JWT stand for?",
                "options": ["Java Web Token", "JSON Web Token", "JavaScript Web Tool", "JSON Wrapper Type"],
                "correct_answer_index": 1,
                "explanation": "JWT = JSON Web Token. A compact, signed token format for authentication.",
                "difficulty": "Easy"
            },
            {
                "question_text": "Which is more secure for storing passwords: plain text or bcrypt hash?",
                "options": [
                    "Plain text is faster",
                    "bcrypt hash",
                    "Both are equally secure",
                    "Plain text is fine if encrypted at rest"
                ],
                "correct_answer_index": 1,
                "explanation": "bcrypt is a slow, salted hashing algorithm designed for password storage. Plain text is never secure.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is OAuth 2.0?",
                "options": [
                    "A programming language",
                    "An authorization framework that lets apps act on behalf of users without sharing passwords",
                    "A type of database",
                    "A frontend framework"
                ],
                "correct_answer_index": 1,
                "explanation": "OAuth 2.0 is an authorization standard. 'Sign in with Google' is a common use case.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the difference between authentication and authorization?",
                "options": [
                    "They are the same",
                    "Authentication = who you are; Authorization = what you can do",
                    "Authentication = password; Authorization = username",
                    "Authorization is faster"
                ],
                "correct_answer_index": 1,
                "explanation": "Authentication verifies identity (login). Authorization determines permissions (what you can access).",
                "difficulty": "Easy"
            }
        ],
        "TypeScript": [
            {
                "question_text": "What is TypeScript?",
                "options": [
                    "A separate programming language",
                    "A typed superset of JavaScript that compiles to plain JavaScript",
                    "A CSS framework",
                    "A database query language"
                ],
                "correct_answer_index": 1,
                "explanation": "TypeScript adds static types to JavaScript. It compiles to plain JS that runs anywhere JS runs.",
                "difficulty": "Easy"
            },
            {
                "question_text": "How do you declare a typed variable in TypeScript?",
                "options": ["var x: int = 5", "let x: number = 5", "int x = 5", "x: number = 5"],
                "correct_answer_index": 1,
                "explanation": "`let x: number = 5` is the standard syntax. The type `number` (lowercase) is TS-specific.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the difference between `interface` and `type` in TypeScript?",
                "options": [
                    "No difference at all",
                    "Both define types, with some syntactic differences; interface is extendable, type supports unions",
                    "interface is faster",
                    "type is for JavaScript only"
                ],
                "correct_answer_index": 1,
                "explanation": "Both define object shapes. interface uses `extends`, type supports `|` unions and `&` intersections.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What does `any` type mean in TypeScript?",
                "options": [
                    "The variable doesn't exist",
                    "The variable can be any type - bypasses type checking",
                    "The variable is always null",
                    "The variable is an array"
                ],
                "correct_answer_index": 1,
                "explanation": "`any` opts out of type checking for that variable. Use sparingly as it defeats TypeScript's purpose.",
                "difficulty": "Easy"
            }
        ],
        "Node.js": [
            {
                "question_text": "What is Node.js?",
                "options": [
                    "A JavaScript framework",
                    "A runtime that executes JavaScript on the server side",
                    "A database",
                    "A frontend library"
                ],
                "correct_answer_index": 1,
                "explanation": "Node.js is a JavaScript runtime built on Chrome's V8 engine. It lets you run JS outside the browser.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is npm?",
                "options": [
                    "Node Programming Method",
                    "Node Package Manager - the default package manager for Node.js",
                    "New Project Module",
                    "Network Protocol Manager"
                ],
                "correct_answer_index": 1,
                "explanation": "npm (Node Package Manager) is the world's largest software registry for JavaScript packages.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is the difference between require and import in Node.js?",
                "options": [
                    "No difference",
                    "require is CommonJS (old), import is ES Modules (modern)",
                    "import is faster",
                    "require is for React only"
                ],
                "correct_answer_index": 1,
                "explanation": "require() is CommonJS (older Node.js). import is ES Modules (modern JS, also used in frontend).",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is Express.js?",
                "options": [
                    "A database",
                    "A minimal and flexible Node.js web application framework",
                    "A testing library",
                    "A frontend framework"
                ],
                "correct_answer_index": 1,
                "explanation": "Express is the most popular Node.js framework for building web servers and APIs.",
                "difficulty": "Easy"
            }
        ],
        "AWS": [
            {
                "question_text": "What does AWS stand for?",
                "options": ["Advanced Web Services", "Amazon Web Services", "Amazon Web Solutions", "Applied Web Systems"],
                "correct_answer_index": 1,
                "explanation": "AWS = Amazon Web Services. The world's largest cloud computing platform.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is Amazon EC2?",
                "options": [
                    "Email service",
                    "Elastic Compute Cloud - provides resizable virtual servers in the cloud",
                    "A database service",
                    "A content delivery network"
                ],
                "correct_answer_index": 1,
                "explanation": "EC2 (Elastic Compute Cloud) provides scalable virtual machines in AWS.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is Amazon S3?",
                "options": [
                    "A serverless compute service",
                    "Simple Storage Service - object storage with high availability",
                    "A SQL database",
                    "A monitoring tool"
                ],
                "correct_answer_index": 1,
                "explanation": "S3 (Simple Storage Service) is object storage for files, images, backups, etc.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the AWS Free Tier?",
                "options": [
                    "A paid trial",
                    "Free usage limits of many AWS services for new accounts (12 months or always free)",
                    "A free VPN service",
                    "A one-time signup bonus"
                ],
                "correct_answer_index": 1,
                "explanation": "AWS Free Tier offers limited free usage of many services, either for 12 months or always free tier (e.g. Lambda).",
                "difficulty": "Easy"
            }
        ],
        "Cybersecurity": [
            {
                "question_text": "What does HTTPS provide that HTTP does not?",
                "options": [
                    "Faster loading",
                    "Encryption of data in transit",
                    "Better SEO",
                    "Mobile compatibility"
                ],
                "correct_answer_index": 1,
                "explanation": "HTTPS adds TLS/SSL encryption so data in transit can't be read by attackers.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is a SQL injection?",
                "options": [
                    "A type of database",
                    "An attack where malicious SQL code is inserted into a query to manipulate the database",
                    "A way to optimize SQL",
                    "A type of index"
                ],
                "correct_answer_index": 1,
                "explanation": "SQL injection is when attackers insert SQL commands into user input fields, e.g. login forms.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is XSS (Cross-Site Scripting)?",
                "options": [
                    "A way to style web pages",
                    "An attack where malicious scripts are injected into web pages viewed by other users",
                    "A JavaScript framework",
                    "A type of database"
                ],
                "correct_answer_index": 1,
                "explanation": "XSS attacks inject malicious JavaScript into web pages, often through user input.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the principle of least privilege?",
                "options": [
                    "Always give admin access",
                    "Give users only the minimum permissions needed to do their job",
                    "Use strong passwords",
                    "Encrypt all data"
                ],
                "correct_answer_index": 1,
                "explanation": "Least privilege means giving users only the permissions they need - reduces attack surface.",
                "difficulty": "Easy"
            }
        ],
        # HTML/CSS is the very first node in the roadmap, so it is the one skill
        # that must never dead-end: if the model is rate-limited here the user
        # cannot start at all.
        "HTML/CSS": [
            {
                "question_text": "Which CSS property controls the space INSIDE an element, between its content and its border?",
                "options": ["margin", "padding", "border-spacing", "gap"],
                "correct_answer_index": 1,
                "explanation": "padding is the space inside the border. margin is the space outside it.",
                "difficulty": "Easy"
            },
            {
                "question_text": "In Flexbox, which property aligns items along the MAIN axis?",
                "options": ["align-items", "justify-content", "align-content", "flex-wrap"],
                "correct_answer_index": 1,
                "explanation": "justify-content works on the main axis; align-items works on the cross axis.",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which HTML element should wrap the primary navigation links of a page?",
                "options": ["<div>", "<nav>", "<section>", "<aside>"],
                "correct_answer_index": 1,
                "explanation": "<nav> is the semantic element for navigation blocks, which also helps screen readers.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does `box-sizing: border-box` change about an element's width calculation?",
                "options": [
                    "Width excludes padding and border",
                    "Width includes padding and border",
                    "Width includes the margin",
                    "Width is ignored entirely"
                ],
                "correct_answer_index": 1,
                "explanation": "With border-box, the declared width includes padding and border, so a 200px box stays 200px wide.",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which CSS at-rule is used to apply styles only at certain viewport sizes?",
                "options": ["@supports", "@media", "@container", "@import"],
                "correct_answer_index": 1,
                "explanation": "@media queries apply styles conditionally, most commonly on viewport width, and are the basis of responsive design.",
                "difficulty": "Easy"
            },
            {
                "question_text": "Which selector has the HIGHEST specificity?",
                "options": [".card p", "#header", "p", "div.card"],
                "correct_answer_index": 1,
                "explanation": "An ID selector (#header) outranks class and element selectors in CSS specificity.",
                "difficulty": "Medium"
            }
        ],
        "JavaScript": [
            {
                "question_text": "What is the output of `typeof null` in JavaScript?",
                "options": ["null", "undefined", "object", "number"],
                "correct_answer_index": 2,
                "explanation": "Due to a historical bug in JavaScript, typeof null returns 'object'. This was never fixed for backwards compatibility.",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which method adds an element to the END of an array?",
                "options": ["unshift()", "push()", "pop()", "shift()"],
                "correct_answer_index": 1,
                "explanation": "push() adds elements to the end of an array. unshift() adds to the beginning.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is a closure in JavaScript?",
                "options": [
                    "A function that has access to variables from its outer scope",
                    "A way to close the browser window",
                    "An error handling mechanism",
                    "A type of loop"
                ],
                "correct_answer_index": 0,
                "explanation": "A closure is a function that retains access to variables from its enclosing scope even after the outer function has returned.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What does the `async` keyword do in JavaScript?",
                "options": [
                    "Makes a function return a Promise automatically",
                    "Runs code in a separate thread",
                    "Pauses execution",
                    "Enables strict mode"
                ],
                "correct_answer_index": 0,
                "explanation": "The async keyword makes a function return a Promise. When combined with await, it provides cleaner syntax for handling asynchronous operations.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the difference between `let` and `const`?",
                "options": [
                    "let can be reassigned, const cannot",
                    "const can be reassigned, let cannot",
                    "No difference",
                    "let is for numbers, const is for strings"
                ],
                "correct_answer_index": 0,
                "explanation": "Both let and const are block-scoped, but const creates a read-only reference. However, if the const is an object, you can still modify its properties.",
                "difficulty": "Easy"
            }
        ],
        "React": [
            {
                "question_text": "What hook is used to manage state in a functional component?",
                "options": ["useEffect", "useState", "useContext", "useReducer"],
                "correct_answer_index": 1,
                "explanation": "useState is the primary hook for managing local state in functional components. useEffect is for side effects, useContext for global state.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is JSX in React?",
                "options": [
                    "JavaScript XML - syntax for writing HTML-like code in JavaScript",
                    "A new programming language",
                    "A CSS framework",
                    "A database query language"
                ],
                "correct_answer_index": 0,
                "explanation": "JSX (JavaScript XML) is a syntax extension that allows you to write HTML-like markup inside JavaScript files. It gets compiled to regular JavaScript.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does useEffect do when dependency array is empty?",
                "options": [
                    "Runs only once on component mount",
                    "Runs on every render",
                    "Never runs",
                    "Runs on unmount"
                ],
                "correct_answer_index": 0,
                "explanation": "An empty dependency array [] means the effect runs only once when the component mounts, similar to componentDidMount in class components.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the Virtual DOM?",
                "options": [
                    "A lightweight copy of the actual DOM that React uses for efficient updates",
                    "A special HTML element",
                    "A CSS framework",
                    "A database"
                ],
                "correct_answer_index": 0,
                "explanation": "The Virtual DOM is a JavaScript representation of the real DOM. React compares (diffs) the Virtual DOM with the actual DOM to minimize updates.",
                "difficulty": "Medium"
            },
            {
                "question_text": "How do you pass data from parent to child component?",
                "options": ["Props", "State", "Context API", "LocalStorage"],
                "correct_answer_index": 0,
                "explanation": "Props (short for properties) are the primary mechanism for passing data from parent to child components in React.",
                "difficulty": "Easy"
            }
        ],
        "Node.js": [
            {
                "question_text": "What is Express.js?",
                "options": [
                    "A minimal and flexible Node.js web application framework",
                    "A database",
                    "A testing library",
                    "An operating system"
                ],
                "correct_answer_index": 0,
                "explanation": "Express.js is a fast, minimalist web framework for Node.js that provides robust features for web applications and APIs.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is npm?",
                "options": [
                    "Node Package Manager - the default package manager for Node.js",
                    "New Project Manager",
                    "Node Project Module",
                    "Network Package Manager"
                ],
                "correct_answer_index": 0,
                "explanation": "npm (Node Package Manager) is the world's largest software registry and the default package manager for Node.js.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What middleware does Express use for parsing JSON?",
                "options": [
                    "express.json()",
                    "express.parse()",
                    "express.bodyParser()",
                    "express.text()"
                ],
                "correct_answer_index": 0,
                "explanation": "express.json() is built-in middleware that parses incoming requests with JSON payloads. It's based on body-parser.",
                "difficulty": "Easy"
            }
        ]
    }

    if skill_name in fallback_questions:
        return skill_name, fallback_questions[skill_name]

    alias = FALLBACK_SKILL_ALIASES.get(skill_name)
    if alias and alias in fallback_questions:
        return alias, fallback_questions[alias]

    return "", []


# =========================================================
# Quiz Generation Endpoint
# =========================================================

def _persist_and_format(
    db: Session,
    source_skill: str,
    questions: List[Dict[str, Any]],
    limit: int
) -> List[QuizQuestionSchema]:
    """
    Store questions and return them as API schemas.

    Persisting is what makes grading possible at all: /validate looks the
    question up by id to read its correct_answer_index, so an unsaved question
    cannot be graded. Rows are deduped on (skill_name, question_text) so repeat
    generations reuse the existing row instead of growing the table without
    bound. `source_skill` is the skill the questions are actually about and is
    what gets stored and returned.
    """
    formatted: List[QuizQuestionSchema] = []
    seen_ids = set()

    for q in questions:
        if len(formatted) >= limit:
            break

        raw_options = q.get("options", [])
        question_text = q.get("question_text", "Question?")
        correct_index = q.get("correct_answer_index", 0)

        # Discard malformed questions rather than storing an unanswerable one.
        if not raw_options or not isinstance(correct_index, int):
            continue
        if correct_index < 0 or correct_index >= len(raw_options):
            continue

        record = db.query(QuizQuestionModel).filter(
            QuizQuestionModel.skill_name == source_skill,
            QuizQuestionModel.question_text == question_text
        ).first()

        if record is None:
            record = QuizQuestionModel(
                skill_name=source_skill,
                question_text=question_text,
                options=raw_options,
                correct_answer_index=correct_index,
                explanation=q.get("explanation"),
                difficulty=q.get("difficulty", "Medium")
            )
            db.add(record)
            db.flush()  # populate record.id without ending the transaction
        else:
            # Keep the stored answer key in sync with the freshly generated text.
            record.options = raw_options
            record.correct_answer_index = correct_index
            record.explanation = q.get("explanation")

        # Never ship the same question id twice in one quiz or the score
        # denominator gets skewed.
        if str(record.id) in seen_ids:
            continue
        seen_ids.add(str(record.id))

        formatted.append(QuizQuestionSchema(
            id=str(record.id),
            question_text=question_text,
            options=[QuizOptionSchema(id=j, text=opt) for j, opt in enumerate(raw_options)],
            difficulty=record.difficulty or "Medium",
            skill_name=source_skill
        ))

    return formatted


def _questions_from_db(db: Session, skill_name: str, limit: int) -> List[QuizQuestionSchema]:
    """Read already-stored questions for a skill (the schema.sql seed bank)."""
    rows = db.query(QuizQuestionModel).filter(
        QuizQuestionModel.skill_name == skill_name
    ).order_by(func.random()).limit(limit).all()

    formatted: List[QuizQuestionSchema] = []
    for row in rows:
        options = row.options or []
        if not options:
            continue
        if row.correct_answer_index is None or row.correct_answer_index >= len(options):
            continue
        formatted.append(QuizQuestionSchema(
            id=str(row.id),
            question_text=row.question_text,
            options=[QuizOptionSchema(id=j, text=opt) for j, opt in enumerate(options)],
            difficulty=row.difficulty or "Medium",
            skill_name=row.skill_name
        ))
    return formatted


@router.get("/generate/{task_id}", response_model=QuizResponseSchema)
async def generate_quiz(
    task_id: str,
    question_count: int = Query(5, ge=3, le=10),
    user_level: str = Query("intermediate", description="User's skill level: beginner, intermediate, advanced"),
    user_id: Optional[str] = Query(None, description="Optional user ID"),
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db)
):
    """
    Generate a quiz for a specific roadmap task using AI.
    Creates contextual questions based on the skill and user's level.
    """
    # Use authenticated user_id if not provided
    if not user_id and authorization:
        from backend.routers.auth import get_user_id_from_token
        auth_user_id = get_user_id_from_token(authorization)
        if auth_user_id:
            user_id = auth_user_id

    # Get the actual skill for this task from the user's roadmap (not hardcoded)
    skill_name = _get_skill_for_task(task_id, user_id)

    print(f"[Quiz] Generating quiz for task: {task_id}, skill: {skill_name}, level: {user_level}")

    # 1. Preferred source: AI-generated questions for this exact skill.
    formatted_questions: List[QuizQuestionSchema] = []
    generated_by = "ai"

    if llm_client.is_configured:
        ai_questions = await generate_ai_questions(skill_name, question_count, user_level)
        if ai_questions:
            formatted_questions = _persist_and_format(
                db, skill_name, ai_questions, question_count
            )

    # 2. AI unavailable or unusable: reuse questions already stored for this
    #    skill (the seed bank, plus anything a previous generation saved). If
    #    the skill has no bank of its own, try its nearest neighbour -- those
    #    rows keep their own skill_name, so the quiz stays honestly labelled.
    if len(formatted_questions) < MIN_QUIZ_QUESTIONS:
        print(f"[Quiz] Using stored question bank for {skill_name}")
        stored = _questions_from_db(db, skill_name, question_count)
        if len(stored) < MIN_QUIZ_QUESTIONS:
            alias = FALLBACK_SKILL_ALIASES.get(skill_name)
            if alias:
                aliased = _questions_from_db(db, alias, question_count)
                if len(aliased) > len(stored):
                    stored = aliased
        if len(stored) > len(formatted_questions):
            formatted_questions = stored
            generated_by = "question_bank"

    # 3. Nothing stored either: use the hardcoded bank. get_fallback_questions
    #    reports which skill the questions are actually about, and that is what
    #    gets stored and shown -- an off-topic quiz is never relabelled as this
    #    skill, so it can't quietly certify knowledge it never tested.
    if len(formatted_questions) < MIN_QUIZ_QUESTIONS:
        source_skill, fallback = get_fallback_questions(skill_name)
        if fallback:
            print(f"[Quiz] Falling back to hardcoded {source_skill} questions for {skill_name}")
            fb_formatted = _persist_and_format(db, source_skill, fallback, question_count)
            if len(fb_formatted) > len(formatted_questions):
                formatted_questions = fb_formatted
                generated_by = "fallback"

    db.commit()

    if len(formatted_questions) < MIN_QUIZ_QUESTIONS:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                f"No quiz is available for {skill_name} right now. "
                "Question generation is temporarily unavailable - please try again shortly."
            )
        )

    return QuizResponseSchema(
        questions=formatted_questions,
        total_questions=len(formatted_questions),
        passing_score=70,
        generated_by=generated_by
    )


# =========================================================
# Quiz Validation Endpoint
# =========================================================

@router.post("/validate", response_model=QuizValidationResponse)
async def validate_quiz(
    payload: QuizValidationRequest,
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db)
):
    """
    Validate quiz answers and unlock next roadmap node if passed.
    User must score at least 70% to pass and unlock the next task.
    """
    task_id = payload.task_id

    # Derive the user from the bearer token; never trust a body-supplied user_id,
    # or any caller could mark another user's tasks complete.
    token_user_id = get_user_id_from_token(authorization)
    if not token_user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required to submit a quiz."
        )
    user_id = token_user_id

    if not payload.submissions:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No answers submitted."
        )

    # Look up only the submitted questions instead of loading the whole table.
    submitted_ids = []
    for submission in payload.submissions:
        try:
            submitted_ids.append(uuid.UUID(submission.question_id))
        except (ValueError, AttributeError, TypeError):
            # Unparseable id — handled as unknown below (fails closed).
            continue

    question_map = {}
    if submitted_ids:
        rows = db.query(QuizQuestionModel).filter(
            QuizQuestionModel.id.in_(submitted_ids)
        ).all()
        question_map = {str(q.id): q for q in rows}

    # Validate each answer
    results = []
    correct_count = 0

    for submission in payload.submissions:
        question_id = submission.question_id
        selected = submission.selected_answer_index

        q = question_map.get(question_id)
        if q is not None:
            is_correct = selected == q.correct_answer_index

            results.append(QuizResultSchema(
                question_id=question_id,
                is_correct=is_correct,
                correct_answer_index=q.correct_answer_index,
                explanation=q.explanation
            ))

            if is_correct:
                correct_count += 1
        else:
            # Unknown question id — fail closed. Marking these correct is what
            # made every quiz auto-pass at 100% regardless of the answers given.
            results.append(QuizResultSchema(
                question_id=question_id,
                is_correct=False,
                correct_answer_index=-1,
                explanation="This question could not be verified, so it was marked incorrect."
            ))

    # Calculate score
    total_questions = len(results)
    score_percentage = int((correct_count / total_questions * 100)) if total_questions > 0 else 0
    passing_score = 70

    passed = score_percentage >= passing_score

    # If passed, mark task as completed and determine next task
    task_unlocked = False
    next_task_id = None

    if passed:
        # Mark current task as completed
        try:
            existing = db.query(TaskProgressModel).filter(
                TaskProgressModel.user_id == uuid.UUID(user_id),
                TaskProgressModel.task_id == task_id
            ).first()

            if existing:
                existing.is_completed = True
                existing.completed_at = datetime.utcnow()
            else:
                new_progress = TaskProgressModel(
                    user_id=uuid.UUID(user_id),
                    task_id=task_id,
                    is_completed=True,
                    completed_at=datetime.utcnow()
                )
                db.add(new_progress)

            # Determine next task from the user's actual roadmap
            next_task_id = _get_next_task_id_for_user(db, user_id, task_id)

            if next_task_id:
                task_unlocked = True

            db.commit()

            # CRITICAL: Invalidate the in-memory roadmap cache so the next
            # request rebuilds the roadmap with the new task completion status.
            _invalidate_roadmap_cache(user_id)

            # Update the persisted roadmap so the completion state survives
            # server restarts.
            _update_persisted_roadmap_progress(user_id, task_id, is_completed=True)

        except Exception as e:
            db.rollback()
            print(f"[Quiz] Error updating progress: {e}")

    return QuizValidationResponse(
        passed=passed,
        score_percentage=score_percentage,
        correct_answers=correct_count,
        total_questions=total_questions,
        results=results,
        task_unlocked=task_unlocked,
        next_task_id=next_task_id,
        message=_get_pass_message(passed, score_percentage, next_task_id)
    )


def _get_next_task_id(current_task_id: str) -> Optional[str]:
    """Determine the next task in the roadmap sequence (fallback - static)."""
    task_sequence = TASK_SEQUENCE

    try:
        current_index = task_sequence.index(current_task_id)
        if current_index < len(task_sequence) - 1:
            return task_sequence[current_index + 1]
    except ValueError:
        pass

    return None


def _get_next_task_id_for_user(db: Session, user_id: str, current_task_id: str) -> Optional[str]:
    """
    Determine the next task in the user's actual persisted roadmap.

    The AI-generated roadmap may have different task IDs than the static
    TASK_SQUENCE, so we must look at the user's actual roadmap to find the
    next task after the one that was just completed.
    """
    try:
        from backend.shared.user_data_db import get_active_roadmap
        persisted_roadmap = get_active_roadmap(user_id)
        if persisted_roadmap:
            all_task_ids = []
            for phase in persisted_roadmap.get("phases", []):
                for task in phase.get("tasks", []):
                    task_id = task.get("id")
                    if task_id:
                        all_task_ids.append(task_id)

            if current_task_id in all_task_ids:
                current_index = all_task_ids.index(current_task_id)
                if current_index < len(all_task_ids) - 1:
                    return all_task_ids[current_index + 1]
    except Exception as e:
        print(f"[Quiz] Note: Could not determine next task from roadmap ({e})")

    # Fall back to static sequence
    return _get_next_task_id(current_task_id)


def _invalidate_roadmap_cache(user_id: str) -> None:
    """
    Invalidate the in-memory roadmap cache for a user.
    This forces the next request to rebuild the roadmap with fresh data.
    """
    try:
        from backend.routers.roadmap import _ROADMAP_CACHE
        keys_to_remove = [key for key in _ROADMAP_CACHE.keys() if key.startswith(f"{user_id}::")]
        for key in keys_to_remove:
            del _ROADMAP_CACHE[key]
            print(f"[Quiz] Invalidated roadmap cache key: {key}")
    except Exception as e:
        print(f"[Quiz] Note: Could not invalidate cache ({e})")


def _update_persisted_roadmap_progress(user_id: str, task_id: str, is_completed: bool) -> None:
    """
    Update the user's persisted roadmap to mark a task as completed.
    This ensures the next-page-load shows the right state.
    """
    try:
        from backend.shared.user_data_db import get_active_roadmap
        from backend.database import SessionLocal
        from backend.shared.models import UserRoadmapModel
        import json

        persisted_roadmap = get_active_roadmap(user_id)
        if not persisted_roadmap:
            return

        # Find and update the task in the persisted roadmap
        for phase in persisted_roadmap.get("phases", []):
            for task in phase.get("tasks", []):
                if task.get("id") == task_id:
                    task["is_completed"] = is_completed
                    task["progress_pct"] = 100 if is_completed else 0
                    break

        # Recalculate phase progress
        for phase in persisted_roadmap.get("phases", []):
            tasks = phase.get("tasks", [])
            if tasks:
                completed_count = sum(1 for t in tasks if t.get("is_completed"))
                phase["progress_pct"] = int((completed_count / len(tasks)) * 100)
                if completed_count == len(tasks):
                    phase["status"] = "Completed"
                elif completed_count > 0:
                    phase["status"] = "In Progress"

        # Recalculate overall completion
        all_phases = persisted_roadmap.get("phases", [])
        if all_phases:
            overall = int(sum(p.get("progress_pct", 0) for p in all_phases) / len(all_phases))
            summary = persisted_roadmap.get("summary", {})
            summary["overall_completion_pct"] = overall

        # Save the updated roadmap back to DB
        db = SessionLocal()
        try:
            user_uuid = uuid.UUID(user_id)
            record = db.query(UserRoadmapModel).filter(
                UserRoadmapModel.user_id == user_uuid,
                UserRoadmapModel.is_active == True
            ).first()

            if record:
                record.roadmap_data = persisted_roadmap
                record.updated_at = datetime.utcnow()
                db.commit()
                print(f"[Quiz] Updated persisted roadmap for user {user_id}")
        finally:
            db.close()
    except Exception as e:
        print(f"[Quiz] Note: Could not update persisted roadmap ({e})")


def _get_pass_message(passed: bool, score: int, next_task: Optional[str]) -> str:
    """Generate user-friendly message based on quiz result."""
    if passed:
        if next_task:
            return f"🎉 Congratulations! You passed with {score}%! The next node has been unlocked."
        else:
            return f"🎉 Congratulations! You've completed the roadmap with {score}%!"
    else:
        return f"📚 You scored {score}%. You need 70% to pass. Review the resources and try again!"


# =========================================================
# Quiz Status Endpoint
# =========================================================

@router.get("/status/{task_id}", response_model=SkillQuizStatusResponse)
def get_quiz_status(
    task_id: str,
    user_id: str = Query(...),
    db: Session = Depends(get_db)
):
    """
    Get the current quiz status for a specific task.
    """
    user_uuid = uuid.UUID(user_id)

    # Check task progress
    task_progress = db.query(TaskProgressModel).filter(
        TaskProgressModel.user_id == user_uuid,
        TaskProgressModel.task_id == task_id
    ).first()

    is_completed = task_progress.is_completed if task_progress else False

    # Check if this is the first task (always unlocked)
    is_unlocked = task_id == "task-p1-1"

    # If not first task, check if previous task is completed
    if not is_unlocked:
        prev_task_id = _get_previous_task_id(task_id)
        if prev_task_id:
            prev_progress = db.query(TaskProgressModel).filter(
                TaskProgressModel.user_id == user_uuid,
                TaskProgressModel.task_id == prev_task_id
            ).first()
            is_unlocked = prev_progress.is_completed if prev_progress else False

    # Get quiz attempts for this task
    skill_name = _get_skill_for_task(task_id)
    attempts = db.query(QuizAttemptModel).join(QuizQuestionModel).filter(
        QuizAttemptModel.user_id == user_uuid,
        QuizQuestionModel.skill_name == skill_name
    ).all()

    total_attempts = len(attempts)
    best_score = None

    if attempts:
        correct_count = sum(1 for a in attempts if a.is_correct)
        unique_questions = len(set(str(a.quiz_question_id) for a in attempts))
        if unique_questions > 0:
            best_score = int((correct_count / unique_questions) * 100)

    return SkillQuizStatusResponse(
        task_id=task_id,
        skill_name=skill_name,
        is_unlocked=is_unlocked,
        is_completed=is_completed,
        best_score=best_score,
        total_quizzes_taken=total_attempts
    )


def _get_previous_task_id(task_id: str) -> Optional[str]:
    """Get the previous task in the roadmap sequence."""
    task_sequence = TASK_SEQUENCE

    try:
        current_index = task_sequence.index(task_id)
        if current_index > 0:
            return task_sequence[current_index - 1]
    except ValueError:
        pass

    return None


def _get_skill_for_task(task_id: str, user_id: Optional[str] = None) -> str:
    """
    Map task_id to skill name.

    Priority:
    1. Look up the task in the user's actual persisted roadmap (has real skill_name)
    2. Fall back to the hardcoded TASK_SKILL_MAP
    3. Default to "JavaScript" if nothing found
    """
    # First, try to get the actual skill from the user's active roadmap
    if user_id:
        try:
            from backend.shared.user_data_db import get_active_roadmap
            persisted_roadmap = get_active_roadmap(user_id)
            if persisted_roadmap:
                # Search through all phases and tasks
                for phase in persisted_roadmap.get("phases", []):
                    for task in phase.get("tasks", []):
                        if task.get("id") == task_id:
                            skill = task.get("skill_name")
                            if skill:
                                return skill
        except Exception as e:
            print(f"[Quiz] Note: Could not load from persisted roadmap ({e})")

    # Fall back to the static map
    return TASK_SKILL_MAP.get(task_id, "JavaScript")
