"""
Quiz Router for SkillTwin Roadmap
Handles AI-powered quiz generation, validation, and node unlocking for roadmap progression.
"""

import uuid
import json
import re
from datetime import datetime
from typing import List, Optional, Dict, Any, Tuple
from fastapi import APIRouter, Depends, Query, HTTPException, status, Header
from sqlalchemy import func
from sqlalchemy.orm import Session
from pydantic import BaseModel

from backend.database import get_db
from backend.shared.models import (
    QuizQuestionModel,
    QuizAttemptModel,
    TaskProgressModel,
    TASK_SKILL_MAP,
    TASK_SEQUENCE
)
from backend.routers.auth import get_user_id_from_token
from backend.shared.llm_client import llm_client

router = APIRouter(
    prefix="/api/quiz",
    tags=["AI Quiz System for Roadmap Progression"]
)


# =========================================================
# Pydantic Schemas
# =========================================================

class QuizOptionSchema(BaseModel):
    id: int
    text: str


class QuizQuestionSchema(BaseModel):
    id: str
    question_text: str
    options: List[QuizOptionSchema]
    difficulty: str
    skill_name: str


class QuizSubmissionSchema(BaseModel):
    question_id: str
    selected_answer_index: int


class QuizResultSchema(BaseModel):
    question_id: str
    is_correct: bool
    correct_answer_index: int
    explanation: Optional[str]


class QuizResponseSchema(BaseModel):
    questions: List[QuizQuestionSchema]
    total_questions: int
    passing_score: int  # Percentage required to pass
    generated_by: str = "ai"  # Indicates if generated by AI


class QuizValidationRequest(BaseModel):
    user_id: str
    task_id: str  # The roadmap task this quiz is for
    submissions: List[QuizSubmissionSchema]
    time_taken_seconds: Optional[int] = None


class QuizValidationResponse(BaseModel):
    passed: bool
    score_percentage: int
    correct_answers: int
    total_questions: int
    results: List[QuizResultSchema]
    task_unlocked: bool
    next_task_id: Optional[str] = None
    message: str


class SkillQuizStatusResponse(BaseModel):
    task_id: str
    skill_name: str
    is_unlocked: bool
    is_completed: bool
    best_score: Optional[int] = None
    total_quizzes_taken: int


# =========================================================
# AI Quiz Generation System
# =========================================================

# Skill descriptions for context-aware question generation
SKILL_CONTEXTS = {
    "HTML/CSS": "Fundamentals of web development including semantic HTML5, CSS3, Flexbox, Grid, responsive design, and modern CSS features like custom properties.",
    "JavaScript": "Core JavaScript including ES6+ features, async/await, promises, DOM manipulation, closures, prototypes, and modern browser APIs.",
    "React": "React library including functional components, hooks (useState, useEffect, useContext), JSX, state management, component patterns, and React 18 features.",
    "TypeScript": "TypeScript type system including interfaces, generics, utility types, type guards, and best practices for type-safe React applications.",
    "Redux": "Redux state management including Redux Toolkit, slices, createAsyncThunk, and modern state management patterns.",
    "Node.js": "Server-side JavaScript with Node.js including Express.js, REST API design, middleware patterns, and server architecture.",
    "Python/FastAPI": "Python web frameworks with FastAPI including path operations, Pydantic models, dependency injection, and async programming.",
    "Authentication": "Web authentication including JWT tokens, OAuth, password hashing with bcrypt, session management, and security best practices.",
    "PostgreSQL": "Relational database with PostgreSQL including SQL queries, joins, aggregations, indexing, transactions, and database design patterns.",
    "ORM": "Object-Relational Mapping with SQLAlchemy including models, relationships, migrations, queries, and efficient database access patterns.",
    "Docker": "Containerization with Docker including Dockerfiles, images, containers, docker-compose, multi-stage builds, and deployment.",
    "CI/CD": "Continuous Integration/Deployment with GitHub Actions including workflows, testing automation, and deployment pipelines.",
    "Testing": "Software testing including unit tests, integration tests, Jest, React Testing Library, and test-driven development.",
    "Security": "Web application security including OWASP Top 10, XSS, CSRF, SQL injection prevention, and secure coding practices.",
    "Portfolio": "Personal portfolio website development with responsive design, deployment, and showcasing projects.",
    "E-commerce": "Building e-commerce applications with shopping carts, product filtering, state management, and payment integration basics.",
    "Backend": "Backend development concepts including REST APIs, server architecture, database integration, and API security.",
    "Database": "Database design and management including relational modeling, SQL, indexing strategies, and data integrity.",
    "DevOps": "DevOps practices including containerization, CI/CD pipelines, cloud deployment, and infrastructure management.",
    "Capstone": "Full-stack application development combining all learned skills into a production-ready capstone project."
}


async def generate_ai_questions(
    skill_name: str,
    question_count: int = 5,
    user_level: str = "intermediate"
) -> List[Dict[str, Any]]:
    """
    Generate quiz questions using AI (OpenRouter/LLM).
    Creates contextual, relevant questions based on the skill and user's level.
    """
    skill_context = SKILL_CONTEXTS.get(skill_name, f"General {skill_name} concepts")

    system_prompt = """You are an expert technical educator creating quiz questions for a skill development platform.
Generate multiple-choice quiz questions that test practical knowledge, not just theoretical facts.
Each question should have exactly 4 options with one clearly correct answer.
Include a brief explanation for why the correct answer is right.

IMPORTANT: Return your response as valid JSON in this exact format:
{
    "questions": [
        {
            "question_text": "The question here?",
            "options": ["Option A", "Option B", "Option C", "Option D"],
            "correct_answer_index": 0,
            "explanation": "The correct answer is A because...",
            "difficulty": "Easy/Medium/Hard"
        }
    ]
}

Make questions practical and relevant to real-world coding scenarios."""

    user_prompt = f"""Generate {question_count} multiple-choice quiz questions about {skill_name}.
Skill context: {skill_context}
User level: {user_level}

Create questions that:
1. Test practical understanding, not just memorization
2. Include realistic scenarios a developer might encounter
3. Have one clearly correct answer
4. Have plausible but incorrect distractors

Return only the JSON format specified."""

    try:
        result = await llm_client.extract_structured_json(
            messages=[{"role": "user", "content": user_prompt}],
            system_prompt=system_prompt
        )

        if result.get("error"):
            print(f"[Quiz AI] Error generating questions: {result['error']}")
            return []

        data = result.get("data", {})
        questions = data.get("questions", [])

        print(f"[Quiz AI] Generated {len(questions)} questions for {skill_name}")
        return questions

    except Exception as e:
        print(f"[Quiz AI] Exception generating questions: {e}")
        return []


# =========================================================
# Fallback Questions (when AI fails or for demo)
# =========================================================

# Minimum number of questions a quiz must contain to be worth grading. Below
# this a single lucky guess swings the score past the 70% pass mark.
MIN_QUIZ_QUESTIONS = 3

# When a skill has no question bank of its own, fall back to the closest skill
# that does. Only genuinely adjacent topics are listed: an off-topic quiz that
# still unlocks the next node is worse than no quiz at all, so a skill with no
# sensible neighbour is deliberately absent and yields a 503 instead.
FALLBACK_SKILL_ALIASES: Dict[str, str] = {
    "Frontend": "HTML/CSS",
    "Portfolio": "HTML/CSS",
    "TypeScript": "JavaScript",
    "Redux": "React",
    "E-commerce": "React",
    "Backend": "Node.js",
    "ORM": "PostgreSQL",
    "Database": "PostgreSQL",
    "DevOps": "Docker",
    "CI/CD": "Docker",
}


def get_fallback_questions(skill_name: str) -> Tuple[str, List[Dict[str, Any]]]:
    """
    Hardcoded questions for when AI generation is unavailable.

    Returns (source_skill, questions). The source skill is the skill the
    questions are actually about, which is not always the skill that was asked
    for -- callers must store and display that value rather than the requested
    one, or a Docker quiz ends up full of JavaScript questions labelled Docker.
    Returns ("", []) when nothing on-topic exists.
    """
    fallback_questions = {
        # HTML/CSS is the very first node in the roadmap, so it is the one skill
        # that must never dead-end: if the model is rate-limited here the user
        # cannot start at all.
        "HTML/CSS": [
            {
                "question_text": "Which CSS property controls the space INSIDE an element, between its content and its border?",
                "options": ["margin", "padding", "border-spacing", "gap"],
                "correct_answer_index": 1,
                "explanation": "padding is the space inside the border. margin is the space outside it.",
                "difficulty": "Easy"
            },
            {
                "question_text": "In Flexbox, which property aligns items along the MAIN axis?",
                "options": ["align-items", "justify-content", "align-content", "flex-wrap"],
                "correct_answer_index": 1,
                "explanation": "justify-content works on the main axis; align-items works on the cross axis.",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which HTML element should wrap the primary navigation links of a page?",
                "options": ["<div>", "<nav>", "<section>", "<aside>"],
                "correct_answer_index": 1,
                "explanation": "<nav> is the semantic element for navigation blocks, which also helps screen readers.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does `box-sizing: border-box` change about an element's width calculation?",
                "options": [
                    "Width excludes padding and border",
                    "Width includes padding and border",
                    "Width includes the margin",
                    "Width is ignored entirely"
                ],
                "correct_answer_index": 1,
                "explanation": "With border-box, the declared width includes padding and border, so a 200px box stays 200px wide.",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which CSS at-rule is used to apply styles only at certain viewport sizes?",
                "options": ["@supports", "@media", "@container", "@import"],
                "correct_answer_index": 1,
                "explanation": "@media queries apply styles conditionally, most commonly on viewport width, and are the basis of responsive design.",
                "difficulty": "Easy"
            },
            {
                "question_text": "Which selector has the HIGHEST specificity?",
                "options": [".card p", "#header", "p", "div.card"],
                "correct_answer_index": 1,
                "explanation": "An ID selector (#header) outranks class and element selectors in CSS specificity.",
                "difficulty": "Medium"
            }
        ],
        "JavaScript": [
            {
                "question_text": "What is the output of `typeof null` in JavaScript?",
                "options": ["null", "undefined", "object", "number"],
                "correct_answer_index": 2,
                "explanation": "Due to a historical bug in JavaScript, typeof null returns 'object'. This was never fixed for backwards compatibility.",
                "difficulty": "Medium"
            },
            {
                "question_text": "Which method adds an element to the END of an array?",
                "options": ["unshift()", "push()", "pop()", "shift()"],
                "correct_answer_index": 1,
                "explanation": "push() adds elements to the end of an array. unshift() adds to the beginning.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is a closure in JavaScript?",
                "options": [
                    "A function that has access to variables from its outer scope",
                    "A way to close the browser window",
                    "An error handling mechanism",
                    "A type of loop"
                ],
                "correct_answer_index": 0,
                "explanation": "A closure is a function that retains access to variables from its enclosing scope even after the outer function has returned.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What does the `async` keyword do in JavaScript?",
                "options": [
                    "Makes a function return a Promise automatically",
                    "Runs code in a separate thread",
                    "Pauses execution",
                    "Enables strict mode"
                ],
                "correct_answer_index": 0,
                "explanation": "The async keyword makes a function return a Promise. When combined with await, it provides cleaner syntax for handling asynchronous operations.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the difference between `let` and `const`?",
                "options": [
                    "let can be reassigned, const cannot",
                    "const can be reassigned, let cannot",
                    "No difference",
                    "let is for numbers, const is for strings"
                ],
                "correct_answer_index": 0,
                "explanation": "Both let and const are block-scoped, but const creates a read-only reference. However, if the const is an object, you can still modify its properties.",
                "difficulty": "Easy"
            }
        ],
        "React": [
            {
                "question_text": "What hook is used to manage state in a functional component?",
                "options": ["useEffect", "useState", "useContext", "useReducer"],
                "correct_answer_index": 1,
                "explanation": "useState is the primary hook for managing local state in functional components. useEffect is for side effects, useContext for global state.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is JSX in React?",
                "options": [
                    "JavaScript XML - syntax for writing HTML-like code in JavaScript",
                    "A new programming language",
                    "A CSS framework",
                    "A database query language"
                ],
                "correct_answer_index": 0,
                "explanation": "JSX (JavaScript XML) is a syntax extension that allows you to write HTML-like markup inside JavaScript files. It gets compiled to regular JavaScript.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What does useEffect do when dependency array is empty?",
                "options": [
                    "Runs only once on component mount",
                    "Runs on every render",
                    "Never runs",
                    "Runs on unmount"
                ],
                "correct_answer_index": 0,
                "explanation": "An empty dependency array [] means the effect runs only once when the component mounts, similar to componentDidMount in class components.",
                "difficulty": "Medium"
            },
            {
                "question_text": "What is the Virtual DOM?",
                "options": [
                    "A lightweight copy of the actual DOM that React uses for efficient updates",
                    "A special HTML element",
                    "A CSS framework",
                    "A database"
                ],
                "correct_answer_index": 0,
                "explanation": "The Virtual DOM is a JavaScript representation of the real DOM. React compares (diffs) the Virtual DOM with the actual DOM to minimize updates.",
                "difficulty": "Medium"
            },
            {
                "question_text": "How do you pass data from parent to child component?",
                "options": ["Props", "State", "Context API", "LocalStorage"],
                "correct_answer_index": 0,
                "explanation": "Props (short for properties) are the primary mechanism for passing data from parent to child components in React.",
                "difficulty": "Easy"
            }
        ],
        "Node.js": [
            {
                "question_text": "What is Express.js?",
                "options": [
                    "A minimal and flexible Node.js web application framework",
                    "A database",
                    "A testing library",
                    "An operating system"
                ],
                "correct_answer_index": 0,
                "explanation": "Express.js is a fast, minimalist web framework for Node.js that provides robust features for web applications and APIs.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What is npm?",
                "options": [
                    "Node Package Manager - the default package manager for Node.js",
                    "New Project Manager",
                    "Node Project Module",
                    "Network Package Manager"
                ],
                "correct_answer_index": 0,
                "explanation": "npm (Node Package Manager) is the world's largest software registry and the default package manager for Node.js.",
                "difficulty": "Easy"
            },
            {
                "question_text": "What middleware does Express use for parsing JSON?",
                "options": [
                    "express.json()",
                    "express.parse()",
                    "express.bodyParser()",
                    "express.text()"
                ],
                "correct_answer_index": 0,
                "explanation": "express.json() is built-in middleware that parses incoming requests with JSON payloads. It's based on body-parser.",
                "difficulty": "Easy"
            }
        ]
    }

    if skill_name in fallback_questions:
        return skill_name, fallback_questions[skill_name]

    alias = FALLBACK_SKILL_ALIASES.get(skill_name)
    if alias and alias in fallback_questions:
        return alias, fallback_questions[alias]

    return "", []


# =========================================================
# Quiz Generation Endpoint
# =========================================================

def _persist_and_format(
    db: Session,
    source_skill: str,
    questions: List[Dict[str, Any]],
    limit: int
) -> List[QuizQuestionSchema]:
    """
    Store questions and return them as API schemas.

    Persisting is what makes grading possible at all: /validate looks the
    question up by id to read its correct_answer_index, so an unsaved question
    cannot be graded. Rows are deduped on (skill_name, question_text) so repeat
    generations reuse the existing row instead of growing the table without
    bound. `source_skill` is the skill the questions are actually about and is
    what gets stored and returned.
    """
    formatted: List[QuizQuestionSchema] = []
    seen_ids = set()

    for q in questions:
        if len(formatted) >= limit:
            break

        raw_options = q.get("options", [])
        question_text = q.get("question_text", "Question?")
        correct_index = q.get("correct_answer_index", 0)

        # Discard malformed questions rather than storing an unanswerable one.
        if not raw_options or not isinstance(correct_index, int):
            continue
        if correct_index < 0 or correct_index >= len(raw_options):
            continue

        record = db.query(QuizQuestionModel).filter(
            QuizQuestionModel.skill_name == source_skill,
            QuizQuestionModel.question_text == question_text
        ).first()

        if record is None:
            record = QuizQuestionModel(
                skill_name=source_skill,
                question_text=question_text,
                options=raw_options,
                correct_answer_index=correct_index,
                explanation=q.get("explanation"),
                difficulty=q.get("difficulty", "Medium")
            )
            db.add(record)
            db.flush()  # populate record.id without ending the transaction
        else:
            # Keep the stored answer key in sync with the freshly generated text.
            record.options = raw_options
            record.correct_answer_index = correct_index
            record.explanation = q.get("explanation")

        # Never ship the same question id twice in one quiz or the score
        # denominator gets skewed.
        if str(record.id) in seen_ids:
            continue
        seen_ids.add(str(record.id))

        formatted.append(QuizQuestionSchema(
            id=str(record.id),
            question_text=question_text,
            options=[QuizOptionSchema(id=j, text=opt) for j, opt in enumerate(raw_options)],
            difficulty=record.difficulty or "Medium",
            skill_name=source_skill
        ))

    return formatted


def _questions_from_db(db: Session, skill_name: str, limit: int) -> List[QuizQuestionSchema]:
    """Read already-stored questions for a skill (the schema.sql seed bank)."""
    rows = db.query(QuizQuestionModel).filter(
        QuizQuestionModel.skill_name == skill_name
    ).order_by(func.random()).limit(limit).all()

    formatted: List[QuizQuestionSchema] = []
    for row in rows:
        options = row.options or []
        if not options:
            continue
        if row.correct_answer_index is None or row.correct_answer_index >= len(options):
            continue
        formatted.append(QuizQuestionSchema(
            id=str(row.id),
            question_text=row.question_text,
            options=[QuizOptionSchema(id=j, text=opt) for j, opt in enumerate(options)],
            difficulty=row.difficulty or "Medium",
            skill_name=row.skill_name
        ))
    return formatted


@router.get("/generate/{task_id}", response_model=QuizResponseSchema)
async def generate_quiz(
    task_id: str,
    question_count: int = Query(5, ge=3, le=10),
    user_level: str = Query("intermediate", description="User's skill level: beginner, intermediate, advanced"),
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db)
):
    """
    Generate a quiz for a specific roadmap task using AI.
    Creates contextual questions based on the skill and user's level.
    """
    skill_name = _get_skill_for_task(task_id)

    print(f"[Quiz] Generating quiz for task: {task_id}, skill: {skill_name}, level: {user_level}")

    # 1. Preferred source: AI-generated questions for this exact skill.
    formatted_questions: List[QuizQuestionSchema] = []
    generated_by = "ai"

    if llm_client.is_configured:
        ai_questions = await generate_ai_questions(skill_name, question_count, user_level)
        if ai_questions:
            formatted_questions = _persist_and_format(
                db, skill_name, ai_questions, question_count
            )

    # 2. AI unavailable or unusable: reuse questions already stored for this
    #    skill (the seed bank, plus anything a previous generation saved). If
    #    the skill has no bank of its own, try its nearest neighbour -- those
    #    rows keep their own skill_name, so the quiz stays honestly labelled.
    if len(formatted_questions) < MIN_QUIZ_QUESTIONS:
        print(f"[Quiz] Using stored question bank for {skill_name}")
        stored = _questions_from_db(db, skill_name, question_count)
        if len(stored) < MIN_QUIZ_QUESTIONS:
            alias = FALLBACK_SKILL_ALIASES.get(skill_name)
            if alias:
                aliased = _questions_from_db(db, alias, question_count)
                if len(aliased) > len(stored):
                    stored = aliased
        if len(stored) > len(formatted_questions):
            formatted_questions = stored
            generated_by = "question_bank"

    # 3. Nothing stored either: use the hardcoded bank. get_fallback_questions
    #    reports which skill the questions are actually about, and that is what
    #    gets stored and shown -- an off-topic quiz is never relabelled as this
    #    skill, so it can't quietly certify knowledge it never tested.
    if len(formatted_questions) < MIN_QUIZ_QUESTIONS:
        source_skill, fallback = get_fallback_questions(skill_name)
        if fallback:
            print(f"[Quiz] Falling back to hardcoded {source_skill} questions for {skill_name}")
            fb_formatted = _persist_and_format(db, source_skill, fallback, question_count)
            if len(fb_formatted) > len(formatted_questions):
                formatted_questions = fb_formatted
                generated_by = "fallback"

    db.commit()

    if len(formatted_questions) < MIN_QUIZ_QUESTIONS:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                f"No quiz is available for {skill_name} right now. "
                "Question generation is temporarily unavailable - please try again shortly."
            )
        )

    return QuizResponseSchema(
        questions=formatted_questions,
        total_questions=len(formatted_questions),
        passing_score=70,
        generated_by=generated_by
    )


# =========================================================
# Quiz Validation Endpoint
# =========================================================

@router.post("/validate", response_model=QuizValidationResponse)
async def validate_quiz(
    payload: QuizValidationRequest,
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db)
):
    """
    Validate quiz answers and unlock next roadmap node if passed.
    User must score at least 70% to pass and unlock the next task.
    """
    task_id = payload.task_id

    # Derive the user from the bearer token; never trust a body-supplied user_id,
    # or any caller could mark another user's tasks complete.
    token_user_id = get_user_id_from_token(authorization)
    if not token_user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required to submit a quiz."
        )
    user_id = token_user_id

    if not payload.submissions:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No answers submitted."
        )

    # Look up only the submitted questions instead of loading the whole table.
    submitted_ids = []
    for submission in payload.submissions:
        try:
            submitted_ids.append(uuid.UUID(submission.question_id))
        except (ValueError, AttributeError, TypeError):
            # Unparseable id — handled as unknown below (fails closed).
            continue

    question_map = {}
    if submitted_ids:
        rows = db.query(QuizQuestionModel).filter(
            QuizQuestionModel.id.in_(submitted_ids)
        ).all()
        question_map = {str(q.id): q for q in rows}

    # Validate each answer
    results = []
    correct_count = 0

    for submission in payload.submissions:
        question_id = submission.question_id
        selected = submission.selected_answer_index

        q = question_map.get(question_id)
        if q is not None:
            is_correct = selected == q.correct_answer_index

            results.append(QuizResultSchema(
                question_id=question_id,
                is_correct=is_correct,
                correct_answer_index=q.correct_answer_index,
                explanation=q.explanation
            ))

            if is_correct:
                correct_count += 1
        else:
            # Unknown question id — fail closed. Marking these correct is what
            # made every quiz auto-pass at 100% regardless of the answers given.
            results.append(QuizResultSchema(
                question_id=question_id,
                is_correct=False,
                correct_answer_index=-1,
                explanation="This question could not be verified, so it was marked incorrect."
            ))

    # Calculate score
    total_questions = len(results)
    score_percentage = int((correct_count / total_questions * 100)) if total_questions > 0 else 0
    passing_score = 70

    passed = score_percentage >= passing_score

    # If passed, mark task as completed and determine next task
    task_unlocked = False
    next_task_id = None

    if passed:
        # Mark current task as completed
        try:
            existing = db.query(TaskProgressModel).filter(
                TaskProgressModel.user_id == uuid.UUID(user_id),
                TaskProgressModel.task_id == task_id
            ).first()

            if existing:
                existing.is_completed = True
                existing.completed_at = datetime.utcnow()
            else:
                new_progress = TaskProgressModel(
                    user_id=uuid.UUID(user_id),
                    task_id=task_id,
                    is_completed=True,
                    completed_at=datetime.utcnow()
                )
                db.add(new_progress)

            # Determine next task
            next_task_id = _get_next_task_id(task_id)

            if next_task_id:
                task_unlocked = True

            db.commit()
        except Exception as e:
            db.rollback()
            print(f"[Quiz] Error updating progress: {e}")

    return QuizValidationResponse(
        passed=passed,
        score_percentage=score_percentage,
        correct_answers=correct_count,
        total_questions=total_questions,
        results=results,
        task_unlocked=task_unlocked,
        next_task_id=next_task_id,
        message=_get_pass_message(passed, score_percentage, next_task_id)
    )


def _get_next_task_id(current_task_id: str) -> Optional[str]:
    """Determine the next task in the roadmap sequence."""
    task_sequence = TASK_SEQUENCE

    try:
        current_index = task_sequence.index(current_task_id)
        if current_index < len(task_sequence) - 1:
            return task_sequence[current_index + 1]
    except ValueError:
        pass

    return None


def _get_pass_message(passed: bool, score: int, next_task: Optional[str]) -> str:
    """Generate user-friendly message based on quiz result."""
    if passed:
        if next_task:
            return f"🎉 Congratulations! You passed with {score}%! The next node has been unlocked."
        else:
            return f"🎉 Congratulations! You've completed the roadmap with {score}%!"
    else:
        return f"📚 You scored {score}%. You need 70% to pass. Review the resources and try again!"


# =========================================================
# Quiz Status Endpoint
# =========================================================

@router.get("/status/{task_id}", response_model=SkillQuizStatusResponse)
def get_quiz_status(
    task_id: str,
    user_id: str = Query(...),
    db: Session = Depends(get_db)
):
    """
    Get the current quiz status for a specific task.
    """
    user_uuid = uuid.UUID(user_id)

    # Check task progress
    task_progress = db.query(TaskProgressModel).filter(
        TaskProgressModel.user_id == user_uuid,
        TaskProgressModel.task_id == task_id
    ).first()

    is_completed = task_progress.is_completed if task_progress else False

    # Check if this is the first task (always unlocked)
    is_unlocked = task_id == "task-p1-1"

    # If not first task, check if previous task is completed
    if not is_unlocked:
        prev_task_id = _get_previous_task_id(task_id)
        if prev_task_id:
            prev_progress = db.query(TaskProgressModel).filter(
                TaskProgressModel.user_id == user_uuid,
                TaskProgressModel.task_id == prev_task_id
            ).first()
            is_unlocked = prev_progress.is_completed if prev_progress else False

    # Get quiz attempts for this task
    skill_name = _get_skill_for_task(task_id)
    attempts = db.query(QuizAttemptModel).join(QuizQuestionModel).filter(
        QuizAttemptModel.user_id == user_uuid,
        QuizQuestionModel.skill_name == skill_name
    ).all()

    total_attempts = len(attempts)
    best_score = None

    if attempts:
        correct_count = sum(1 for a in attempts if a.is_correct)
        unique_questions = len(set(str(a.quiz_question_id) for a in attempts))
        if unique_questions > 0:
            best_score = int((correct_count / unique_questions) * 100)

    return SkillQuizStatusResponse(
        task_id=task_id,
        skill_name=skill_name,
        is_unlocked=is_unlocked,
        is_completed=is_completed,
        best_score=best_score,
        total_quizzes_taken=total_attempts
    )


def _get_previous_task_id(task_id: str) -> Optional[str]:
    """Get the previous task in the roadmap sequence."""
    task_sequence = TASK_SEQUENCE

    try:
        current_index = task_sequence.index(task_id)
        if current_index > 0:
            return task_sequence[current_index - 1]
    except ValueError:
        pass

    return None


def _get_skill_for_task(task_id: str) -> str:
    """Map task_id to skill name."""
    return TASK_SKILL_MAP.get(task_id, "JavaScript")
